


export enum Status{
    ONLINE= "ONLINE",
    OFFLINE = "OFFLINE"
}

export enum Role{
    MEMBER= 'MEMBER',
    ADMIN= 'ADMIN'
}

export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",

  // Input & Validation
  BAD_USER_INPUT = "BAD_USER_INPUT",
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // Resource Issues
  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  CONFLICT = "CONFLICT",

  // Server Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",

  // Business Logic
  FORBIDDEN_ACTION = "FORBIDDEN_ACTION",
  RATE_LIMITED = "RATE_LIMITED",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",

  // Messaging Specific
  CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND",
  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  USER_NOT_IN_CONVERSATION = "USER_NOT_IN_CONVERSATION"
}
